[package]
name = "advent_of_code_macro"
version = "0.1.2"
edition = "2021"
description = "An test generating macro for advent of code"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.9"
