name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_2020:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd 2020 && cargo build --verbose
    - name: Run tests
      run: cd 2020 && cargo test --verbose
      
  tests_2021:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd 2021 && cargo build --verbose
    - name: Run tests
      run: cd 2021 && cargo test --verbose
